#!/bin/bash

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J get_variants

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU
##SBATCH -A MRC-EPID-CCLD-SL2-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --exclusive

##SBATCH --exclude=cpu-d-[25-30]

#! Specify required run time
#SBATCH --time=2:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#SBATCH --output=slurm-%x-%j.out

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

module load gcc/5
module load stata/14

cd /home/mdp50/rds/rds-rjh234-mrc-epid/Studies/People/Maik/pGWAS_SomaLogic/03_explained_variance/data

## call the STATA script
stata -b ../scripts/03_get_variants.do

