#!/bin/bash
#!

### Extract regions and regional sentinel variants 
### To run: while read pheno; do echo ${pheno}; sbatch 05_SBATCH_getregions ${pheno}; done < /rds/project/rjh234/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/phenotypelist_4979.txt

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J GETREGIONS

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#! Specify required run time
#SBATCH --time=100:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#SBATCH --output=slurm-%x-%j.out

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location 
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

export pheno=${1}

#5e-8/4979 = 1.004e-11

cd /rds/project/rjh234/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Post_GWAS/01_regional_sentinel_variants

rm /rds/project/rjh234/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Post_GWAS/01_regional_sentinel_variants/regions/${pheno}_regions.txt
rm /rds/project/rjh234/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Post_GWAS/01_regional_sentinel_variants/regional_sentinel_variants/${pheno}_regional_sentinels.txt

zcat ~/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Meta-Analysis/Fenland_auto_chrX_filtered/output/${pheno}_Fenland_MA_auto_chrX_filtered.txt.gz | awk '{if(NR==1) print $0; else if(NR>1 && ($11+0.0) <= (1.004e-11 + 0) && ($17 + 0) >= 5000 && $5+0.0 >= 0.01 && $5+0.0 <= 0.99 ) print $0}' OFS="\t" | sed '1d'  | awk '{print $18,$19,$19}' OFS="\t" | sort -k1,1 -k 2,2n | awk '{if($1+0.0==6+0 && $2+0 >= 25500000+500000 && $2+0 <= 34000000-500000) {print $1,25500000,34000000} else if($1+0.0==6+0 && $2+0 >= 25500000 && $2+0 <= 25500000+500000) {print $1,$2-500000,34000000} else if($1+0.0==6+0 && $2+0 >= 34000000-500000 && $2+0 <= 34000000) {print $1,25500000,$2+500000}  else if($2-500000 >= 0) {print $1,$2-500000,$2+500000} else {print $1,0,$2+500000} }' OFS="\t" | ~/rds/rds-rjh234-mrc-epid/Programs/bedtools2/bin/bedtools merge -i stdin > regions/${pheno}_regions.txt

while read chr start end; do zcat ~/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Meta-Analysis/Fenland_auto_chrX_filtered/output/${pheno}_Fenland_MA_auto_chrX_filtered.txt.gz | awk '{if(NR==1) print $0; else if(NR>1 && ($11+0.0) <= (1.004e-11 + 0) && ($17 + 0) >= 5000 && $5+0.0 >= 0.01 && $5+0.0 <= 0.99 ) print $0}' OFS="\t" | sed '1d' | awk -v chr=${chr} -v start=${start} -v end=${end} '{if(($18+0)==(chr+0) && ($19+0) >= (start+0) && ($19+0) <= (end+0)) print}' | awk -v pheno=${pheno} -v start=${start} -v end=${end} -v max=0 '{if(sqrt(($9/$10)*($9/$10))>=max){want=$0; max=sqrt(($9/$10)*($9/$10))}} END{print pheno,want,start,end}' OFS="\t" ; done < regions/${pheno}_regions.txt > regional_sentinel_variants/${pheno}_regional_sentinels.txt

echo "Done."


