#!/bin/bash
#!
#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

###
### TO RUN: for i in {1..22}; do for j in $(ls -1 chr${i}/parts/OMICS_Phase1_res_invnX_chr${i}.out-part* | perl -pe 's{\-part}{\t}g' | cut -f2); do echo ${i} ${j}; sbatch 02_02_SBATCH_splitparts ${i} ${j}; done; done

###

#! Name of the job:
#SBATCH -J SPLITFILES

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --cpus-per-task 1

#SBATCH --output=slurm-%x-%j.out

#! Specify required run time
#SBATCH --time=100:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4

#! Insert additional module load commands after this line if needed:
#! ############################################################


export chr=${1}
export part=${2}
echo "Chromosome... " ${chr}
echo "Part..." ${part}

cd /home/ew248/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/bgenie1.3/Fenland-OMICS/output/formatted/chr${chr}

mkdir splitparts
#Remove previous files
echo "Removing old files..."
rm splitparts/*_chr${chr}_part${part}.txt.gz

#Extract columns from each part to make a separate file for each phenotype and concatenate to make a single file for each phenotype

i=0
for pheno in `cat`; do
echo ${i} ${pheno} ${part}
start=$(( 8+(4*${i}) ))
end=$(( 8+(4*${i})+3 ))
cut -f 1-7,${start}-${end} parts/OMICS_Phase1_res_invnX_chr${chr}.out-part${part}  -d\  | gzip >> splitparts/${pheno}_chr${chr}_part${part}.txt.gz
i=$((i+1))
done < /home/ew248/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/phenotypelist_4979.txt

echo "Done."


