#!/bin/bash
#!
#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

###
### TO RUN: for i in {1..22}; do sbatch 02_01_SBATCH_makeparts ${i}; done
###

#! Name of the job:
#SBATCH -J MAKEPARTS

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --cpus-per-task 20

#! Specify required run time
#SBATCH --time=100:00:00

#SBATCH --output=slurm-%x-%j.out

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4

#! Insert additional module load commands after this line if needed:
#! ############################################################

export chr=${1}
echo "Chromosome... " ${chr}

#Make formatted directory and create directories for each chromosome before running
cd /home/ew248/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/bgenie1.3/Fenland-OMICS/output/formatted/chr${chr}

#Remove previous files
echo "Removing previous files..."
rm -rf parts; mkdir parts

#Split the output file into parts, each with 20,000 lines
echo "Splitting file..."
zcat ../../OMICS_Phase1_res_invnX_chr${chr}.out.gz | split -l 20000 - parts/OMICS_Phase1_res_invnX_chr${chr}.out-part

echo "Done."




