#!/bin/bash
#!

## script to look up variants in a specific region
# Submit jobs
# while IFS= read -r line; do sbatch scripts/02_look_up_SOMAmers $line; done < input/SOMAscan.v4.ma.files

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J SNP-look_up_SOMAmer

#! Which project should be charged:
##SBATCH -A MRC-EPID-SL0-CPU
#SBATCH -A MRC-EPID-CCLD-SL2-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --cpus-per-task 4

## restrict the number of nodes to be used (maximum of 30)
#SBATCH --exclude=cpu-d-[25-30]

#! Specify required run time
#SBATCH --time=10:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
##SBATCH -p epid
#SBATCH -p clincloud

#! ############################################################
#! Modify the settings below to specify the application's environment, location 
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

module load gcc/5

## export variables
export SL=${1}
export SFILE=~/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Meta-Analysis/Fenland_auto_chrX_filtered/output

echo "Do look-up for ${SL}"

## set the directory
cd /home/mdp50/rds/rds-rjh234-mrc-epid/Studies/People/Maik/pGWAS_SomaLogic/07_pQTL_classification/input

## look up SNP in SOMAscan data (impose a p-value filter to speed up the look-up, ensure that possible characters are converted to numeric)
zcat ${SFILE}/${SL} | awk '$11 + 0 <= 5e-8 {print $0}' - | grep -wf pQTL.query.txt - | awk -v prot=$SL '{print prot"\t"$0}' > ../output/${SL}.lookup

