#!/bin/bash

## script to generate a protein GGM
 
#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J protein_GGM

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU
##SBATCH -A MRC-EPID-CCLD-SL2-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --exclusive

##SBATCH --exclude=cpu-d-[25-30]

#! Specify required run time
#SBATCH --time=10:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#SBATCH --output=slurm-%x-%j.out

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid
##SBATCH -p clincloud

#! ############################################################
#! Modify the settings below to specify the application's environment, location
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

module load gcc/5
module load r-3.6.0-gcc-5.4.0-bzuuksv

## run the R script
scripts/03_generate_GGM.R
