#!/bin/bash
#!

###
### To run: while read pheno; do echo ${pheno}; sbatch 04_SBATCH_format ${pheno}; done < /home/ew248/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/phenotypelist_4979.txt
###

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J FORMATMA

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#! Specify required run time
#SBATCH --time=100:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#SBATCH --output=slurm-%x-%j.out

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location 
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

# Add chromosome, position & rsid to output file and filter to SNPs with N>5,000 (ie. present in theee largest subset)

export pheno=${1}
echo ${pheno}

cat ../Fenland/${pheno}/${pheno}_METAANALYSIS_Fenland-OMICS-Corexome-GWAS_1.tbl.gz <(zcat ../Fenland_chrX/${pheno}/${pheno}_METAANALYSIS_Fenland-OMICS-Corexome-GWAS_chrX_1.tbl.gz | sed '1d' | gzip) | zcat | wc -l

cat ../Fenland/${pheno}/${pheno}_METAANALYSIS_Fenland-OMICS-Corexome-GWAS_1.tbl.gz <(zcat ../Fenland_chrX/${pheno}/${pheno}_METAANALYSIS_Fenland-OMICS-Corexome-GWAS_chrX_1.tbl.gz | sed '1d' | gzip) | zcat | paste <(cut -f 2 markername_rsid_1to22X_Fenland-OMICS.txt) - | awk '{if(NR==1) print $0; else if(NR > 1 && $17+0 >= 5000) print $0}' | awk '{if(NR==1){gsub("-", "" , $11) ; print $0,"chr","pos"} else {split($2, a, ":") ; $(NF+1)=a[1]; split(a[2], b, "_") ; $(NF+1)=b[1]; print }}' OFS="\t" | awk '{if(NR==1){print $0} else if(NR>1) {gsub("chr","",$18); print $0} }' OFS="\t" | gzip > output/${pheno}_Fenland_MA_auto_chrX_filtered.txt.gz

zcat output/${pheno}_Fenland_MA_auto_chrX_filtered.txt.gz | wc -l

echo "Done."


